// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://nehlmeomtpytwjsdunez.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Im5laGxtZW9tdHB5dHdqc2R1bmV6Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTU5NTI2NjAsImV4cCI6MjA3MTUyODY2MH0.ML6PR1ERc-VOFid1yiihO8oKCE639hQpM6vEv7uqC1E";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});